version: "3.7"

services:
  redis:
    ports:
      - "127.0.0.1:6379:6379"
  bridge0:
    ports:
      - "127.0.0.1:5001:5001"

  bridge1:
    ports:
      - "127.0.0.1:5002:5002"

  nginx:
    environment:
      CONTAINER_NAME: bridge
      APP_QTY: 2
    depends_on:
      - bridge0
      - bridge1
